spring:
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:3306/medvollapi
    username: medvollapi
    password: medvollapi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true           # Exibir as queries SQL geradas no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  data:
    web:
      pageable:
        page-parameter: pagina    # Define o nome do parâmetro de número da página
        size-parameter: tamanho   # Define o nome do parâmetro de tamanho da página
      sort:
        sort-parameter: ordem     # Define o nome do parâmetro de ordenação

server:
  error:
    include-stacktrace: never     # Exibe o stacktrace completo nos erros

api:
  security:
    token:
      secret: "${API_SECURITY_TOKEN_SECRET:MedVol123@}" # Lê o segredo de uma variável de ambiente se não achar usa a Chave Secreta depois dos :